name: build

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Java 8
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 8
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Execute Gradle check
      env:
        ORG_GRADLE_PROJECT_ossrhUsername: xxx
        ORG_GRADLE_PROJECT_ossrhPassword: xxx
      run: ./gradlew check
